### PR TITLE
PS1 Enhancement Request

### PR DESCRIPTION
**Pull request by kapoor1992**
Hello Sir,

I have found an area of great concern, which I would like to humbly provide a solution for. It took me a while to research the right way to handle this logic, and I think this way is appropriate.

I hope this finds you well,

Dhruv

### CODE REVIEW

**Comment by cristian-conte** [comment]
Great find @kapoor1992 ! One note though, should both comments in that block be changed to # Replace ? There's a space after the # in other comments.

**Comment by foontzoot** [comment]
> Great find @kapoor1992 ! One note though, should both comments in that block be changed to # Replace ? There's a space after the # in other comments.

In that case, I assume, more very careful research is required.

**Comment by kapoor1992** [comment]
Hello Mr. Christian and Professor Siniser,

Thank you for your prompt code reviews and excellent pieces of advice. I heeded your advice and made the changes after I stumbled across [a new research device](https://en.wikipedia.org/wiki/Internet).

Warm regards,
Dhruv

**Comment by zmeghji** [comment]
Clearly I need to check my github notifications more frequently. Many thanks @kapoor1992  for this critical fix. Welcome to the ScaleUpFunction community.

**Pull request merged**
